name = "navsphere"
compatibility_date = "2024-11-11"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[env.production.vars]
GITHUB_CLIENT_ID = "Ov23liD21dTD4s6c0x1q"
GITHUB_OWNER = "wtyicy"
GITHUB_REPO = "NavSphere"
GITHUB_BRANCH = "main"
NEXTAUTH_URL = "http://nav.wtyicyai.com/api/auth"
NEXT_PUBLIC_API_URL="http://nav.wtyicyai.com/"

